wechange_payments/urls.py
# -*- coding: utf-8 -*-
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::
"""

from django.urls import path
from wechange_payments.views import api, frontend

urlpatterns = [
    path('account/contribution/', frontend.overview, name='overview'),
    path('account/contribution/payment/', frontend.payment, name='payment'),
    path('account/contribution/payment/update/', frontend.payment_update, name='payment-update'),
    path('account/contribution/payment/<int:pk>/process/', frontend.payment_process, name='payment-process'),
    path('account/contribution/payment/<int:pk>/success/', frontend.payment_success, name='payment-success'),
    path('account/contribution/payment/infos/', frontend.payment_infos, name='payment-infos'),
    path('account/contribution/mine/', frontend.my_subscription, name='my-subscription'),
    path('account/contribution/suspended/', frontend.suspended_subscription, name='suspended-subscription'),
    #path('account/contribution/past/', frontend.past_subscriptions, name='past-subscriptions'),
    path('account/contribution/cancel/', frontend.cancel_subscription, name='cancel-subscription'),
    path('account/contribution/debug-delete/', frontend.debug_delete_subscription, name='debug-delete-subscription'),
    path('account/invoices/', frontend.invoices, name='invoices'),
    path('account/invoices/<int:pk>/', frontend.invoice_detail, name='invoice-detail'),
    path('account/invoices/<int:pk>/download/', frontend.invoice_download, name='invoice-download'),
    path('account/additional_invoices/<int:pk>/download/', frontend.additional_invoice_download, name='additional-invoice-download'),
    path('account/payl_stats/', frontend.admin_stats, name='admin-stats'),
    
    #path('payments/api/payment/', api.make_payment, name='api-make-payment'),
    path('payments/api/subscription-payment/', api.make_subscription_payment, name='api-make-subscription-payment'),
    path('payments/api/subscription-change-amount/', api.subscription_change_amount, name='api-subscription-change-amount'),
    path('payments/api/success_endpoint/', api.success_endpoint, name='api-success-endpoint'),
    path('payments/api/error_endpoint/', api.error_endpoint, name='api-error-endpoint'),
    path('payments/api/postback_endpoint/', api.postback_endpoint, name='api-postback-endpoint'),
    path('payments/api/snooze-popup/', api.snooze_popup, name='api-snooze-popup'),
]

wechange_payments/models.py
# -*- coding: utf-8 -*-

import logging

from annoying.functions import get_object_or_None
from dateutil import relativedelta
from django.db import models
from django.contrib import admin
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _, ngettext
from django_countries.fields import CountryField

from wechange_payments.conf import settings, PAYMENT_TYPE_DIRECT_DEBIT, \
    PAYMENT_TYPE_CREDIT_CARD, PAYMENT_TYPE_PAYPAL
from wechange_payments.utils.utils import _get_invoice_filename
from datetime import timedelta


logger = logging.getLogger('wechange-payments')

USERPROFILE_SETTING_POPUP_CLOSED = 'payment_popup_closed_date'
USERPROFILE_SETTING_POPUP_CLOSED_TIMES = 'payment_popup_closed_times'
# False or missing means "existing user"
# True means newly registered user (after payments were introduced) who hasn't clicked away the popup ever
USERPROFILE_SETTING_POPUP_USER_IS_NEW = 'payment_popup_user_registered_after_payments'


class DebitPeriodMixin:
    """Mixin for Payments and Subscriptions debit_period field."""

    # debit period choices
    DEBIT_PERIOD_MONTHLY = 'm'
    DEBIT_PERIOD_QUARTER_YEARLY = 'q'
    DEBIT_PERIOD_HALF_YEARLY = 'h'
    DEBIT_PERIOD_YEARLY = 'y'
    DEBIT_PERIODS = {
        DEBIT_PERIOD_MONTHLY: _('monthly'),
        DEBIT_PERIOD_QUARTER_YEARLY: _('quarterly'),
        DEBIT_PERIOD_HALF_YEARLY: _('half-yearly'),
        DEBIT_PERIOD_YEARLY: _('yearly'),
    }
    DEBIT_PERIOD_CHOICES = [(k, v) for k, v in DEBIT_PERIODS.items()]

    # conversion to number of months
    DEBIT_PERIOD_MONTHS = {
        DEBIT_PERIOD_MONTHLY: 1,
        DEBIT_PERIOD_QUARTER_YEARLY: 3,
        DEBIT_PERIOD_HALF_YEARLY: 6,
        DEBIT_PERIOD_YEARLY: 12,
    }

    @property
    def debit_period_months(self):
        """Get debit_periods number of months."""
        return self.DEBIT_PERIOD_MONTHS[self.debit_period]

    @property
    def debit_period_schedule(self):
        """Helper to debit_period schedule translations."""
        return ngettext(
            'every month', 'every %(months)s months', self.debit_period_months
        ) % {'months': self.debit_period_months}

    @property
    @admin.display(description=_('Debiting Amount'))
    def debit_amount(self):
        """Actual payment amount computed from the monthly amount and the debit_period."""
        return self.amount * self.debit_period_months

    @property
    def is_monthly(self):
        return self.debit_period == self.DEBIT_PERIOD_MONTHLY


class Payment(DebitPeriodMixin, models.Model):
    """ 
        Payment model.
        
        State `STATUS_PREAUTHORIZED_UNPAID` is a special state, where a future payment
            has been authorized and saved at the payment proveider, and only needs a special
            API call to confirm and "cash in" the payment. 
            This is used for postponed subscriptions, that are created while a current 
            subscription is still running.
    """
    
    TYPE_CHOICES = (
        (PAYMENT_TYPE_DIRECT_DEBIT, _('Direct Debit (SEPA)')),
        (PAYMENT_TYPE_CREDIT_CARD, _('Credit Card')),
        (PAYMENT_TYPE_PAYPAL, _('PayPal')),
    )
    
    STATUS_NOT_STARTED = 0
    STATUS_STARTED = 1
    STATUS_COMPLETED_BUT_UNCONFIRMED = 2
    STATUS_PAID = 3
    STATUS_PREAUTHORIZED_UNPAID = 301
    STATUS_FAILED = 101
    STATUS_RETRACTED = 102
    STATUS_CANCELED = 103
    
    STATUS_CHOICES = (
        (STATUS_NOT_STARTED, _('Not started')),
        (STATUS_STARTED, _('Payment initiated but not completed by user yet')),
        (STATUS_COMPLETED_BUT_UNCONFIRMED, _('Payment processing')),
        (STATUS_PAID, _('Successfully paid')),
        (STATUS_PREAUTHORIZED_UNPAID, _('Pre-authorized for payment, but not yet paid')),
        (STATUS_FAILED, _('Failed')),
        (STATUS_RETRACTED, _('Retracted')),
        (STATUS_CANCELED, _('Canceled')),
    )
    
    # payments with this status are "done", signalling that
    # further payments may be made on a subscription
    FINALIZED_STATUSES = (
        STATUS_FAILED,
        STATUS_PAID,
    )
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False,
        related_name='payments', on_delete=models.CASCADE, null=True)
    subscription = models.ForeignKey('wechange_payments.Subscription', editable=False,
        related_name='payments', on_delete=models.SET_NULL, blank=True, null=True)
    
    vendor_transaction_id = models.CharField(_('Vendor Transaction Id'), max_length=50,
        help_text='An Id for the payment generated by the Payment Service')
    internal_transaction_id = models.CharField(_('Internal Transaction Id'), max_length=50,
        help_text='An Id for the payment generated by us')
    amount = models.FloatField(default='0.0', verbose_name=_('Monthly Amount'))
    debit_period = models.CharField(_('Debiting Period'), max_length = 50,
        default=DebitPeriodMixin.DEBIT_PERIOD_MONTHLY, choices=DebitPeriodMixin.DEBIT_PERIOD_CHOICES)
    type = models.CharField(_('Payment Type'), blank=False,
        default=PAYMENT_TYPE_DIRECT_DEBIT, choices=TYPE_CHOICES, editable=False, max_length=50)
    last_action_at = models.DateTimeField(verbose_name=_('Last Action At'), editable=False, auto_now=True)
    completed_at = models.DateTimeField(verbose_name=_('Completed At'), editable=False, blank=True, null=True)
    status = models.PositiveSmallIntegerField(_('Payment Status'), blank=False,
        default=STATUS_NOT_STARTED, choices=STATUS_CHOICES, editable=False)
    
    is_reference_payment = models.BooleanField(verbose_name=_('Is reference payment'), default=True, editable=False, 
        help_text='Is this the reference (first) payment in a series or a subscription payment derived from a reference payment?') 
    is_postponed_payment = models.BooleanField(verbose_name=_('Is postponed payment'), default=False, editable=False, 
        help_text='Is this a postponed payment, that gets pre-authorized first, and then cashed-in at some later point?') 
    revoked = models.BooleanField(verbose_name=_('Has been revoked'), default=False)
    
    # billing address details, can be saved for some payment methods, but not necessary
    first_name = models.CharField(blank=True, null=True, max_length=255)
    last_name = models.CharField(blank=True, null=True, max_length=255)
    organisation = models.CharField(blank=True, null=True, max_length=255)
    email = models.EmailField(blank=True, null=True)
    address = models.CharField(blank=True, null=True, max_length=255)
    city = models.CharField(blank=True, null=True, max_length=255)
    postal_code = models.CharField(blank=True, null=True, max_length=255)
    country = CountryField(blank=True, null=True)
    
    backend = models.CharField(_('Backend class used'), max_length=255)
    extra_data = models.JSONField(null=True, blank=True, encoder=DjangoJSONEncoder)
    
    class Meta(object):
        app_label = 'wechange_payments'
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')
    
    def get_type_string(self):
        return dict(self.TYPE_CHOICES).get(self.type)
    
    def get_admin_change_url(self):
        """ Returns the django admin edit page for this object. """
        return reverse('admin:wechange_payments_payment_change', kwargs={'object_id': self.id})


class TransactionLog(models.Model):
    
    TYPE_REQUEST = 0
    TYPE_POSTBACK = 1
    
    #: Choices for :attr:`type`: ``(int, str)``
    TYPE_CHOICES = (
        (TYPE_REQUEST, _('Direct Request')),
        (TYPE_POSTBACK, _('Received Postback')),
    )
    
    created = models.DateTimeField(verbose_name=_('Created'), editable=False, auto_now_add=True)
    url = models.CharField(_('API Endpoint URL'), max_length=150, null=True, blank=True)
    type = models.PositiveSmallIntegerField(_('Transaction Type'), blank=False,
        default=TYPE_REQUEST, choices=TYPE_CHOICES, editable=False)
    data = models.JSONField(encoder=DjangoJSONEncoder)
    
    class Meta(object):
        app_label = 'wechange_payments'
        verbose_name = _('Payment Transaction Log')
        verbose_name_plural = _('Payment Transaction Logs')
        
    def get_admin_change_url(self):
        """ Returns the django admin edit page for this object. """
        return reverse('admin:wechange_payments_transactionlog_change', kwargs={'object_id': self.id})


class Subscription(DebitPeriodMixin, models.Model):
    """
        Subscription model. Has an initial reference payment which can be used
        to book further payments from a provider.
        The `state` of the subscription is extremely important, as it determines
        if further payments can be made from it. 
        The `next_due_date` determines if a further payment may be made at this time.
        
        States mostly exclusive, meaning if for a user, one subscription of that state
        exists, no more for that users with the same state(s) can also exist.
        This is enforced in the `save()` method.
        The two "current" states 1 and 2 are mutually exclusive, and while there is
        an active 2 subscription, there can never be a waiting (3) subscription!
        Check `EXLUSIVE_STATE_MAP` to for a full list of exclusive states.
        
        ### State transition overview:
        
        A listing of all cases that can happen, where Subscriptions are created
        or are transitioning states for one specific user.
        * Sub is a newly created Subscription (after a successful payment)
        * S<n> are existing Subscriptions with the state <n>.
        * Cycle(<result>) is the daily call to `process_due_subscription_payments` to book
            due subscription payments
        * Pattern is: <precondition> + <addition> --> <result>
        
        Case A: If PAYMENTS_POSTPONED_PAYMENTS_IMPLEMENTED == False:
        ---------------

wechange_payments/templates/wechange_payments/base.html
{% extends "cosinnus/base.html" %}
{% load i18n static cosinnus_tags %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a class="active" href="{% url 'wechange-payments:overview' %}">{% trans "Payments" context "(BS1)" %}</a></li>
{% endblock breadcrumb %}

{% block extrahead %}
	{% if SETTINGS.DEBUG %}
		<link rel="stylesheet/less" href="{% static "less/payments.less" %}">
		<script src="{% static "js/vendor/less.min.js" %}"></script>
	{% else %}
    	<link href="{% static 'css/payments.css' %}" rel="stylesheet">
	{% endif %}
{% endblock %}

{% block page_title %}{% trans "Payments" context "(BS2)" %}{% endblock page_title %}

wechange_payments/templates/wechange_payments/invoices.html
{% extends "wechange_payments/base.html" %}
{% load l10n i18n cosinnus_tags static widget_tweaks %}

{% block page_title %}{% trans "My Invoices" %}{% endblock %}

{% block leftnav %}
	{% include 'wechange_payments/leftnav.html' %}
{% endblock leftnav %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a class="active" href="{% url 'wechange-payments:invoices' %}">{% trans "My Invoices" %}</a></li>
{% endblock %}

{% block content %}
    
    <!-- a box with semi transparent background -->
    <div class="v2-content">
    	<h1>{% trans "Invoices" %}</h1>
    	
    	<p>
    		TODO: invoices
    	</p>
    	{% for invoice in invoices %}
    		{% comment %} TODO: invoice {% endcomment %}
    	{% endfor %}
    	
    </div>
        
    
{% endblock %}

wechange_payments/templates/wechange_payments/my_subscription.html
{% extends "wechange_payments/base.html" %}
{% load l10n i18n cosinnus_tags static widget_tweaks %}

{% block cosinnus_jshead %}
	{{ block.super }}
	
	{% include 'wechange_payments/partials/slider_constants.html' with slider_initial_amount=subscription.amount  debit_period_initial=subscription.debit_period %}
{% endblock %}

{% block extrahead %}
	{{ block.super }}
	
	{% include 'wechange_payments/partials/slider_dependencies.html' %}
{% endblock %}

{% block page_title %}{% trans "Your Contribution" context "(MS1)" %}{% endblock %}

{% block leftnav %}
	{% include 'wechange_payments/leftnav.html' %}
{% endblock leftnav %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a class="active" href="{% url 'wechange-payments:my-subscription' %}">{% trans "Your Contribution" context "(MS1)" %}</a></li>
{% endblock %}

{% block content %}
    
    {% comment %} The 'onkeydown' attribute prevents form sending on enter {% endcomment %}
    <form method="POST" action="{% url "wechange-payments:api-subscription-change-amount" %}" 
    		class="payments-form cosinnus-form form-horizontal large-space" onkeydown="return event.key != 'Enter';">{% csrf_token %}
        
        <!-- a box with semi transparent background -->
        <div class="v2-content">
	        <div class="error-frame alert alert-danger alert-dismissable" style="display: none;">
	            <i class="fa fa-exclamation-triangle fa-3x"></i>
		        <p class="error-message"></p>
		    </div>
		    
		    <h2>
                {% blocktrans with amount=subscription.debit_amount|intify debit_period=subscription.get_debit_period_display context "(MS2)" %}Your current Contribution is {{ amount }} Euro {{ debit_period }}{% endblocktrans %}
                {% if not subscription.is_monthly %}
                    {% blocktrans with amount=subscription.amount|intify context "(MS9)" %}({{ amount }} Euro per month){% endblocktrans %}
                {% endif %}
            </h2>
			<p>
                {% captureas desc_text %}{% blocktrans with portal_name=COSINNUS_CURRENT_PORTAL.name context "(MS3)" %}We understand WECHANGE as a common good: You pay for the use of WECHANGE what it is worth to you. With every Euro you spend, you help us to make WECHANGE better. With an average of 5 Euros per month, we can cover the costs of hosting the platform, everything above contributes directly to further development.

If you can contribute less or nothing at all, we're sure you have good reasons. But please remember: This is only possible because other users support you!{% endblocktrans %}{% endcaptureas %}
                {{ desc_text|linebreaksbr }}
			</p>
			
			{% include "wechange_payments/partials/additional_campaign_header.html" %}
			
			<p>
				<a href="{% include 'wechange_payments/partials/url_learn_more.html' %}" target="_blank">{% trans "Learn more" context "(MS4)" %}</a>
			</p>
			
			{% include "wechange_payments/partials/additional_campaign_section.html" %}
			
			<hr/>
			
			<h3>{% trans "Change your monthly Contribution" context "(MS7)" %}:</h3>
			
        	<div class="large-space">
				<span>
					{% trans "If you would like to change the amount you contribute, you can choose a new amount using the slider. You may also choose a higher amount by entering it manually." context "(MS8)" %}
					{% blocktrans with vat_amount=SETTINGS.PAYMENTS_INVOICE_PROVIDER_TAX_RATE_PERCENT context "(PF24)" %}Contribution amount includes {{ vat_amount }}% VAT.{% endblocktrans %}
				</span>
			</div>

            {% include 'wechange_payments/fields/slider.html' with field_name='amount' %}

            <h3>{% trans "Change your debit period" context "(MS8)" %}:</h3>

            {% include 'wechange_payments/fields/period_slider.html' with field_name='debit_period' %}

			<div class="button-section clearfix">
				{% comment %} Add this to the button to make it initially disabled until the amount is changed:
	                class="enabled-on-change disabled" disabled="disabled">
				{% endcomment %}
                <button type="submit" class="pull-right rounded-button button-color-primary-inverted"> 
			        <span class="rounded-button-inner">
						{% trans "Modify Contribution Amount" context "(MS5)" %}
			        </span>
			    </button>
			    	
				    <a href="{% url "wechange-payments:cancel-subscription" %}" class="pull-left rounded-button button-color-tertiary">
				        <span class="rounded-button-inner">
	                		{% trans "Terminate your Contribution" context "(MS6)" %}
				        </span>
				    </a>
			    {% comment %}  
		    	No changing payment infos here for now
			    <a href="{% url "wechange-payments:payment-update" %}" class="pull-left rounded-button button-color-secondary">
			        <span class="rounded-button-inner">
						{% trans "Change payment information" context "(TS9)" %}
			        </span>
			    </a>
			    {% endcomment %}
			</div>
		    
		</div>
	</form>
        
    
{% endblock %}

wechange_payments/templates/wechange_payments/past_subscriptions.html
{% extends "wechange_payments/base.html" %}
{% load l10n i18n cosinnus_tags static widget_tweaks %}

{% block page_title %}{% trans "Past Contributions" %}{% endblock %}

{% block leftnav %}
	{% include 'wechange_payments/leftnav.html' %}
{% endblock leftnav %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a class="active" href="{% url 'wechange-payments:past-subscriptions' %}">{% trans "Past Contributions" %}</a></li>
{% endblock %}

{% block content %}
    
    <!-- a box with semi transparent background -->
    <div class="v2-content">
    	<h1>{% trans "Past Contributions" %}</h1>
    
    	{% for subscription in past_subscriptions %}
    		{{ subscription.created }} - 
    		<i><span class="moment-data-date" data-date="{{ subscription.next_due_date|date:'c' }}"></span></i>
    		<br/>
    	{% endfor %}
    	
    	
    </div>
        
    
{% endblock %}

wechange_payments/templates/wechange_payments/payment_infos.html
{% extends "wechange_payments/base.html" %}
{% load l10n i18n cosinnus_tags static widget_tweaks %}

{% block page_title %}{% trans "Your payment details" context "(INF1)" %}{% endblock %}

{% block leftnav %}
	{% include 'wechange_payments/leftnav.html' %}
{% endblock leftnav %}

{% block breadcrumb %}
	{{ block.super }}
	<li><a class="active" href="{% url 'wechange-payments:payment-infos' %}">{% trans "Your payment details" context "(INF1)" %}</a></li>
{% endblock %}

{% block content %}
    
    <!-- a box with semi transparent background -->
    <div class="v2-content white-content payment-info-page">
		<h2>{% trans "Your Contribution" context "(INF17)" %}</h2>
    	<div class="large-space">
    		<table>
				<tr>
					<td>{% trans "The last payment was made on" context "(INF10)" %}</td>
					<td>
						{% if last_payment.status < 3 %}
							{% blocktrans with date=last_payment.last_action_at.date|localize context "(INF15)" %}Processing. Started at {{ date }}.{% endblocktrans %}
						{% elif last_payment.status > 3 %}
							{% blocktrans with date=last_payment.last_action_at.date|localize context "(INF16)" %}Attempted at {{ date }}, but not completed.{% endblocktrans %}
						{% else %}
							{{ last_payment.completed_at.date|localize }}
						{% endif %}
					</td>
				</tr>
				<tr>
					<td>{% trans "Amount" context "(INF11)" %}</td>
					<td>{{ last_payment.debit_amount|intify }} € {{ last_payment.get_debit_period_display }}</td>
				</tr>
			</table>
		</div>
		<div class="regular-space">
			{% trans "All information about your past payments can be found in the invoice overview" context "(INF13)" %}:
		</div>
		<div>
    		<a href="{% url "wechange-payments:invoices" %}" class="rounded-button button-color-secondary">
		        <span class="rounded-button-inner">
					{% trans "Show Invoice overview" context "(INF14)" %}
		        </span>
		    </a>
		</div>
		<hr class="invisible" />
		
		{% if subscription.state > 0 %}
		<div class="large-space">
    		<table>
				<tr>
					<td>{% trans "Contribution Status" context "(INF2)" %}</td>
					<td>
						{% if subscription.state == 3 %}
							{% trans "Will become active after your last Contribution expires." context "(INF3-subscription status)" %}
						{% elif subscription.state == 2 %}
							{% trans "Active since" context "(INF4-subscription status)" %}
							{{ subscription.created.date|localize }}
						{% elif subscription.state == 1 %}
							{% comment %} If a newer subscription with state 3 exists, this case won't be shown {% endcomment %}
							{% trans "Cancelled" context "(INF5-subscription status)" %}.
							{% trans "Expires" %}: 
							{{ subscription.next_due_date|localize }}
						{% endif %}
					</td>
				</tr>
				<tr>
					<td>{% trans "Next payment scheduled" context "(INF7)" %}</td>
					<td>
						{% if subscription.state == 1 %}
							-
						{% else %}
							{{ subscription.next_due_date|localize }}
						{% endif %}
					</td>
				</tr>
				{% if subscription.state > 1 %}
					<tr>
						<td>{% trans "Your current contribution" context "(INF6)" %}</td>
						<td>
							<span>{{ subscription.debit_amount|intify }} € {{ subscription.get_debit_period_display }}</span>
						</td>
					</tr>
				{% endif %}
			</table>
		</div>
		<div>
    		<a href="{% url "wechange-payments:payment" %}" class="rounded-button button-color-secondary">
		        <span class="rounded-button-inner">
		        	{% if subscription.state == 1 %}
		        		{% trans "Set up new Contribution" context "(INF8.2)" %}
		        	{% else %}
						{% trans "Adjust or terminate your Contribution" context "(INF8.1)" %}
					{% endif %}
		        </span>
		    </a>
		</div>
		
		{% endif %}
		
		{% if subscription.state > 1 %}
			<hr class=""></hr>
			<hr class="invisible"></hr>
			
			<h2>{% trans "Your payment details" context "(INF1)" %}</h2>
	    	<div class="large-space">
	    		{% include 'wechange_payments/partials/subscription_payment_information.html' with subscription=subscription %}
	    	</div>
	    	
	    	<div>
	    		<a href="{% url "wechange-payments:payment-update" %}" class="rounded-button button-color-secondary">
			        <span class="rounded-button-inner">
						{% trans "Change payment information" context "(TS9)" %}
			        </span>
			    </a>
			</div>
		{% endif %}
		
		{% comment %}  
			Popup explaining payment information
			
			{% captureas content %}
		        <p>
		        	{% trans "To change your payment method or billing address, please cancel the current Contribution and set up a new one!" context "(INF8)" %}
		        </p>
		        <p>
					{% trans "You will only be billed after the current Contribution expires." %} 
		        </p>
			{% endcaptureas %}
			{% captureas custom_button_html %}
				<button type="button" class="submit-btn-x btn btn-emphasized" href="{% if subscription.state == 1 %}{% url "wechange-payments:payment" %}{% else %}{% url "wechange-payments:cancel-subscription" %}{% endif %}">
                    <ul class="media-list">
                        <li class="media">
                            <a class="pull-left" href="#">
                                <i class="fa fa-check"></i>
                            </a>
                            <div class="media-body">
                                {% trans "OK" %}
                            </div>
                        </li>
                    </ul>
                </button>
                <button type="button" class="btn btn-emphasized" data-dismiss="modal">
                    <ul class="media-list">
                        <li class="media">
                            <a class="pull-left" href="#">
                                <i class="fa fa-times"></i>
                            </a>
                            <div class="media-body">
                                {% trans "Cancel" %}
                            </div>
                        </li>
                    </ul>
                </button>
			{% endcaptureas %}
            {% trans "Change payment information" context "(INF1.1)" as title %}
		    {% include "cosinnus/modal_box.html" with id="changePaymentInfoModal" label=content title=title title_icon="fa-credit-card" hide_submit_button=True custom_button_html=custom_button_html %}
		    
			<a class="rounded-button button-color-secondary" href="#" data-toggle="modal" data-target="#changePaymentInfoModal">
		        <span class="rounded-button-inner">
		            {% trans "Change payment informationx" context "(INF1.1)" %}
		        </span>
		    </a>
		
		{% endcomment %}

    	{% comment %}  
    		"Back to PORTAL" and "print as pdf" section, to do later! 
    	
    	<hr/>
    	<div>
    		<a href="{% get_non_cms_root_url %}" class="rounded-button button-color-primary-inverted">
		        <span class="rounded-button-inner">
                    {% blocktrans with portal_name=COSINNUS_CURRENT_PORTAL.name context "(SC8)" %}Back to {{ portal_name }}{% endblocktrans %}
                    TO DO: raus!
		        </span>
		    </a>
		    <a class="pull-right rounded-button button-color-secondary" href="{% url "wechange-payments:payment" %}">
		        <span class="rounded-button-inner">
		            {% trans "Print this page or save as PDF" context "(INF19)" %} (TO DO!)
		            TO DO: als icon
		        </span>
		    </a>
    	</div>
    	{% endcomment %}
    	
    	
    	
    </div>
        
    
{% endblock %}